[package]
name = "words2num2-py"
version.workspace = true
edition.workspace = true

[lib]
name = "_rust"
crate-type = ["cdylib"]

[dependencies]
num2words2-core = { path = "../num2words2-core" }
num-bigint = "0.4"
bigdecimal = "0.4"
pyo3 = { version = "0.23", features = ["extension-module", "abi3-py38", "num-bigint"] }
